export const ADD_DISH = "ADD_DISH";
export const DELETE_DISH = "DELETE_DISH";
export const CHANGE_MODAL_STATE = "CHANGE_MODAL_STATE";
export const FETCH_REQUEST = "FETCH_REQUETS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const DISHES_INIT = "DISHES_INIT";
export const DISHES_INIT_IN_CART = "DISHES_INIT_IN_CART";
